### ISSUE TITLE
Unable to deploy Photon-Controller

### ISSUE THREAD

**Issue by ShaorongChen** [vmware/photon-controller#100] opened 2017-03-15 02:35 UTC
Hi there,

I successfully deployed installer-ova-nv-1.1.1-dfea3bb.ova to my ESXi host running 

![esxihost](https://cloud.githubusercontent.com/assets/6728827/23930986/928fd498-096a-11e7-9ce0-21c43087e7ac.png)
![photoninstallv111](https://cloud.githubusercontent.com/assets/6728827/23931050/f2ad3e88-096a-11e7-8837-47c571f97219.png)

But when I am trying to install lightwave and photo controller using the provided guide it alway failed at the step of creating pc-1 vm.

I have attached the config yaml file and also the log extracted from /var/log in the Photon installer.

[PhotonInstaller_yaml.txt](https://github.com/vmware/photon-controller/files/843227/PhotonInstaller_yaml.txt)
[photon-installer_log.txt](https://github.com/vmware/photon-controller/files/843230/photon-installer_log.txt)

The deployment process stuck at the testing of 
2017-03-14 06:11:02 DEBUG ControllerClusterInstaller:229 - Info: Checking if photon controller service is running at 10.33.146.102 : Count 300
2017-03-14 06:11:03 DEBUG ControllerClusterInstaller:320 - https://10.33.146.102:9000/status
2017-03-14 06:11:04 ERROR ControllerClusterInstaller:234 - Error: The PC node at 10.33.146.102 failed to provide correct status after 300 iterations
2017-03-14 06:11:04 ERROR PhotonSetupImpl:90 - Error: Failed to install Controller Cluster

You see from the screen capture that lightwave was properly spun up. The PC-1 was also spun up but seem the DNS name wasn't set to the what was configured in the yaml file. And https://10.33.146.102:9000/status is not reachable.

![lightwavevm](https://cloud.githubusercontent.com/assets/6728827/23930840/c90b1272-0969-11e7-9c63-e9bc7b660157.png)
![pc-1](https://cloud.githubusercontent.com/assets/6728827/23930842/ceb01ec0-0969-11e7-904c-5c4d89acaebe.png)

Did I make any mistake in my yaml config file? I am new to VMware photon...

Sorry for any inconvenience caused.

**Comment by alancivita** [comment] 2017-03-15 11:50
Hi, the dns entries, a part from lightwave, must point to lightwave ip adress:
in your case
compute:
  hypervisors:
    esxi-1:
      hostname: "lssinh020.sin.sap.corp"
      ipaddress: "10.33.146.88"
      dns: "10.33.139.40"
      credential:
        username: "MyUsername"
        password: "MyPassword"

should be:
compute:
  hypervisors:
    esxi-1:
      hostname: "lssinh020.sin.sap.corp"
      ipaddress: "10.33.146.88"
      dns: "**10.33.146.93**"
      credential:
        username: "MyUsername"
        password: "MyPassword"

same for the pc-1 section:
    pc-1:
      appliance:
        hostref: "esxi-1"
        datastore: "VD0"
        memoryMb: 2048
        cpus: 2
        enable-ssh-root-login: true
        credential:
          username: "root"
          password: "MyPassword"
        network-config:
          type: "static"
          hostname: "LSSINH026.sin.sap.corp"
          ipaddress: "10.33.146.94"
          network: "NAT=VM Network"
          netmask: "255.255.252.192"
          dns: "10.33.139.40,10.33.50.8"
          ntp: "10.33.142.104"
          gateway: "10.33.146.65"
it should be:
    pc-1:
      appliance:
        hostref: "esxi-1"
        datastore: "VD0"
        memoryMb: 2048
        cpus: 2
        enable-ssh-root-login: true
        credential:
          username: "root"
          password: "MyPassword"
        network-config:
          type: "static"
          hostname: "LSSINH026.sin.sap.corp"
          ipaddress: "10.33.146.94"
          network: "NAT=VM Network"
          netmask: "255.255.252.192"
          dns: "**10.33.146.93**"
          ntp: "10.33.142.104"
          gateway: "10.33.146.65"

if you take a look at the docs:
https://github.com/vmware/photon-controller/wiki/Quick-Start-Guide
The value that you must set for the dns entry for each section except lightwave is counterintuitive: Because Photon Controller uses the DNS server that is included with Lightwave, the DNS entry for each section except lightwave must be the static IP address that you are assigning to the Lightwave VM in the lightwave section of the YAML configuration.

Alan

**Comment by ShaorongChen** [comment] 2017-03-16 08:17
Hi Alan,

Thank you for spotting the mistake at the DNS. But it seems the deployment stuck at load balancer deployment stage.

Please find attached yaml and photon-controller.log file
[photon-installer_log.txt](https://github.com/vmware/photon-controller/files/847055/photon-installer_log.txt)
[PhotonInstaller_yaml.txt](https://github.com/vmware/photon-controller/files/847056/PhotonInstaller_yaml.txt)

I tried the deployment multiple time but still failed at load balancer stage.

Sorry for any inconvenience caused.

Regards,
Shaorong Chen

**Comment by alancivita** [comment] 2017-03-16 08:34
Hi, well according to your logs the installation fails at the PC deployment stage:
Error: The PC node at 10.33.146.102 failed to provide correct status after 300 iterations
2017-03-14 06:11:04 ERROR PhotonSetupImpl:90 - Error: Failed to install Controller Cluster
so it can't carry on with the LB because the PC hasn't been deployed yet.

can you check please the number of dns entries on the esx host?
esxcli network ip dns server list
please be sure that there are no more than 2 dns entries, otherwise installation will fail.

Alan

**Comment by ShaorongChen** [comment] 2017-03-16 09:24
Hi Alan,

2017-03-16 08:00:24 DEBUG ControllerClusterInstaller:202 - https://10.33.146.102:9000/deployments/default/set_image_datastores
2017-03-16 08:00:25 INFO  PlatformInstaller:173 - COMPLETE: Install Photon Controller Cluster
2017-03-16 08:00:25 INFO  PlatformInstaller:184 - Installing Load Balancer
2017-03-16 08:00:25 INFO  TaskReporter:19 - Start [Task: Load Balancer Installation]
2017-03-16 08:00:25 DEBUG HaproxyInstaller:89 - Debug: Photon Controller hosts - 10.33.146.102
2017-03-16 08:00:25 INFO  TaskReporter:39 - Info [Task: Load Balancer Installation] : Deploying and Powering on the HaProxy VM on ESXi host: 10.33.146.88
2017-03-16 08:00:25 INFO  HaproxyInstaller:109 - Info: Deploying and Powering on the HaProxy VM on ESXi host: 10.33.146.88
2017-03-16 08:00:25 DEBUG OVFToolHelper:181 - Info: Ovftool deploy OVA to ESX host
2017-03-16 08:00:25 DEBUG OVFToolHelper:182 - /opt/vmware/ovftool/ovftool --name=load-balancer-1 --X:apiVersion=5.5 --acceptAllEulas --noSSLVerify --skipManifestCheck --overwrite --powerOffTarget --powerOn --datastore=VD0 --net:NAT=VM Network --X:injectOvfEnv --prop:ip0=10.33.146.103 --prop:netmask0=255.255.252.192 --prop:gateway0=10.33.146.65 --prop:DNS=10.33.146.104 --prop:root_password=P@ssw0rd11 --prop:photon_password= --prop:lb_hosts=10.33.146.102 --prop:enable_ssh_root_login=true /var/opt/vmware/photon/controller/appliances/loadbalancer.ova-dir/loadbalancer.ovf vi://root@10.33.146.88/
2017-03-16 08:00:25 INFO  TaskReporter:39 - Info [Task: Load Balancer Installation] : Starting appliance deployment
2017-03-16 08:00:25 DEBUG OVFToolHelper:188 - Info: 1489651225363
2017-03-16 08:00:25 DEBUG OVFToolHelper:190 - Opening OVF source: /var/opt/vmware/photon/controller/appliances/loadbalancer.ova-dir/loadbalancer.ovf
2017-03-16 08:00:31 DEBUG OVFToolHelper:190 - Enter login information for target vi://10.33.146.88/
2017-03-16 08:00:31 DEBUG OVFToolHelper:190 - Username: root
2017-03-16 08:00:31 DEBUG OVFToolHelper:190 - Password: **********
2017-03-16 08:00:39 DEBUG OVFToolHelper:190 - Enter login information for target vi://10.33.146.88/
2017-03-16 08:00:39 DEBUG OVFToolHelper:190 - Username: root
2017-03-16 08:09:27 DEBUG OVFToolHelper:190 - Password: 

It actually pass that PC-1 deployment stage. It is stuck at loadbalancer user name root?

**Comment by alancivita** [comment] 2017-03-16 09:32
ah sorry but the last attached log stops at 14/03 :)

**Comment by ShaorongChen** [comment] 2017-03-17 00:56
Hi Alan,

Maybe I have attached the wrong file. Please find the log for 16 March.

[photon-installer.log.txt](https://github.com/vmware/photon-controller/files/849385/photon-installer.log.txt)
[PhotonInstaller_yaml.txt](https://github.com/vmware/photon-controller/files/849386/PhotonInstaller_yaml.txt)

**Comment by mrporcles** [comment] 2017-03-17 17:05
I had a similar problem and it was due to my DNS lookups failing to my primary DNS. Check the forward and reverse lookups for the FQDN's and static IP's you are looking to assign to your LW, PC, LB instances pre install.

**Comment by alancivita** [comment] 2017-03-18 13:00
Hi, 
this doesn't match your config file:
2017-03-16 07:59:15 INFO  TaskReporter:39 - Info [Task: Photon Controller Installation] : Starting appliance deployment
2017-03-16 07:59:15 DEBUG OVFToolHelper:188 - Info: 1489651155815
2017-03-16 07:59:16 DEBUG OVFToolHelper:190 - Opening OVF source: /var/opt/vmware/photon/controller/appliances/photon-controller.ova-dir/photon-controller.ovf
2017-03-16 07:59:16 DEBUG OVFToolHelper:190 - The manifest does not validate
2017-03-16 07:59:23 DEBUG OVFToolHelper:190 - Enter login information for target vi://10.33.146.88/
2017-03-16 07:59:23 DEBUG OVFToolHelper:190 - Username: mlp
2017-03-16 07:59:23 DEBUG OVFToolHelper:190 - Password: **********
2017-03-16 07:59:23 DEBUG OVFToolHelper:190 - Opening VI target: vi://mlp@10.33.146.88:443/
2017-03-16 07:59:23 DEBUG OVFToolHelper:190 - Deploying to VI: vi://mlp@10.33.146.88:443/

the mlp user i mean.
or at least there is something strange: 
this is the PC-1 log:
2017-03-16 07:59:16 DEBUG OVFToolHelper:190 - Opening OVF source: /var/opt/vmware/photon/controller/appliances/photon-controller.ova-dir/photon-controller.ovf
2017-03-16 07:59:16 DEBUG OVFToolHelper:190 - The manifest does not validate
2017-03-16 07:59:23 DEBUG OVFToolHelper:190 - Enter login information for target vi://10.33.146.88/
2017-03-16 07:59:23 DEBUG OVFToolHelper:190 - Username: mlp
2017-03-16 07:59:23 DEBUG OVFToolHelper:190 - Password: **********
2017-03-16 07:59:23 DEBUG OVFToolHelper:190 - Opening VI target: vi://mlp@10.33.146.88:443/
2017-03-16 07:59:23 DEBUG OVFToolHelper:190 - Deploying to VI: vi://mlp@10.33.146.88:443/

this is LB-1 log:
2017-03-16 08:00:25 DEBUG OVFToolHelper:190 - Opening OVF source: /var/opt/vmware/photon/controller/appliances/loadbalancer.ova-dir/loadbalancer.ovf
2017-03-16 08:00:31 DEBUG OVFToolHelper:190 - Enter login information for target vi://10.33.146.88/
2017-03-16 08:00:31 DEBUG OVFToolHelper:190 - Username: root
2017-03-16 08:00:31 DEBUG OVFToolHelper:190 - Password: **********
2017-03-16 08:00:39 DEBUG OVFToolHelper:190 - Enter login information for target vi://10.33.146.88/
2017-03-16 08:00:39 DEBUG OVFToolHelper:190 - Username: root
2017-03-16 08:09:27 DEBUG OVFToolHelper:190 - Password: 

where the root user is used..
don't know if this could cause your issues, but it sounds odd to me

Alan

**Comment by ShaorongChen** [comment] 2017-03-21 06:18
Hi Alan,

Good day!
The load balancer config is using hostref to esxi1 should it automatically use the configure set in similar to lightwave and pc-1?

loadBalancer:
  load-balancer-1:
    appliance:
      hostref: "esxi-1"
      datastore: "VD0"
      memoryMb: 2048
      cpus: 2
      enable-ssh-root-login: true
compute:
  hypervisors:
    esxi-1:
      hostname: "LSSINH020.sin.sap.corp"
      ipaddress: "10.33.146.88"
      dns: "10.33.146.104"
      credential:
        username: "myuser"
        password: "mypassword"

I am bit confused.

Sorry for any inconvenience caused.

Regards,
Shaorong Chen

**Comment by alancivita** [comment] 2017-03-21 07:34
Hi, if you look at the docs, in the quick start page - The anatomy of a configuration file:
this section explains how to use the options: (yes it's a bit confusing, i agree :) )

  controllers:
    pc-1:
      appliance:
        hostref: The target ESXi hypervisor on which you want the Photon Controller 
                 management VM to reside. The hypervisor must be included in the 
                 compute section's list of hypervisors. 
        datastore: The datastore that this VM will use; it must be the name of the 
                   datastore on the ESXi host referenced by the value of the 
                   hostref in the previous line.
        credential:
          **username: The name of the root account of the target hypervisor. 
          password: The password for the root account.** 
        network-config:
          network: "NAT=VM Network"
          type: "static"
          hostname: The fully qualified domain name that you want to set as 
                    the hostname of the Photon Controller management VM. 
          ipaddress: The static IP address you want to assign to the management VM.
          netmask: The netmask that the  management VM will use. 
          dns: The IP address of the DNS server that the management VM will use. 
          ntp: The IP address of the NTP server that the management VM will use. 
          gateway: The gateway IP address that you want the management VM to use. 


let me know
Alan

**Comment by ShaorongChen** [comment] 2017-03-22 02:36
Noted on your details. But the deployment of the LB-1 is failing, The deployment script failed to grab the hypervisor details from hostref: "esxi-1"

[photon-installer.log (2).txt](https://github.com/vmware/photon-controller/files/860199/photon-installer.log.2.txt)
[pc-config.yaml.txt](https://github.com/vmware/photon-controller/files/860200/pc-config.yaml.txt)

Sorry for any inconvenience caused.

**Comment by budgreen619** [comment] 2017-03-29 22:26
I am having the same problem. The photon installer deploys lightwave fine and waits for the "Lightwave OIDC service" to start, which it does. Then it deploys the photon controllers and waits for the photon controller service to be running, but the service never starts on either of the controllers. 'netstat -nap' shows that the controllers are not listening on port 9000. 

can you tell me, what is supposed to be installing/starting the photon controller service? is it pushed out from the photon installer or is it built into the photon controller OVA and supposed to start when the controller boots?

can I start it manually?

2017-03-29 21:59:28 DEBUG ControllerClusterInstaller:320 - https://10.25.199.31:9000/status
2017-03-29 21:59:29 DEBUG ControllerClusterInstaller:229 - Info: Checking if photon controller service is running at 10.25.199.31 : Count 294
2017-03-29 21:59:30 DEBUG ControllerClusterInstaller:320 - https://10.25.199.31:9000/status
2017-03-29 21:59:31 DEBUG ControllerClusterInstaller:229 - Info: Checking if photon controller service is running at 10.25.199.31 : Count 295
2017-03-29 21:59:33 DEBUG ControllerClusterInstaller:320 - https://10.25.199.31:9000/status
2017-03-29 21:59:34 DEBUG ControllerClusterInstaller:229 - Info: Checking if photon controller service is running at 10.25.199.31 : Count 296
2017-03-29 21:59:35 DEBUG ControllerClusterInstaller:320 - https://10.25.199.31:9000/status
2017-03-29 21:59:36 DEBUG ControllerClusterInstaller:229 - Info: Checking if photon controller service is running at 10.25.199.31 : Count 297
2017-03-29 21:59:37 DEBUG ControllerClusterInstaller:320 - https://10.25.199.31:9000/status
2017-03-29 21:59:38 DEBUG ControllerClusterInstaller:229 - Info: Checking if photon controller service is running at 10.25.199.31 : Count 298
2017-03-29 21:59:39 DEBUG ControllerClusterInstaller:320 - https://10.25.199.31:9000/status
2017-03-29 21:59:40 DEBUG ControllerClusterInstaller:229 - Info: Checking if photon controller service is running at 10.25.199.31 : Count 299
2017-03-29 21:59:41 DEBUG ControllerClusterInstaller:320 - https://10.25.199.31:9000/status
2017-03-29 21:59:42 DEBUG ControllerClusterInstaller:229 - Info: Checking if photon controller service is running at 10.25.199.31 : Count 300
2017-03-29 21:59:43 DEBUG ControllerClusterInstaller:320 - https://10.25.199.31:9000/status
2017-03-29 21:59:44 ERROR ControllerClusterInstaller:234 - Error: The PC node at 10.25.199.31 failed to provide correct status after 300 iterations
com.vmware.photon.platform.setup.installer.InstallException: The PC node at 10.25.199.31 failed to provide correct status after 300 iterations

**Comment by budgreen619** [comment] 2017-03-29 22:50
you can follow this post if you want more info. at least in my particular case I can't start the photon controller service because the controller VM isn't joined to the lightwave domain. looks like a DNS problem with lightwave

https://groups.google.com/forum/#!topic/photon-controller/Ah8VPj7Ds7Y

**Comment by mwest44** [comment] 2017-03-29 23:19
We found a couple of regressions that affected LW domain join and pushed a new build on Monday.  Did you download your installer ova before that?

**Comment by budgreen619** [comment] 2017-03-30 14:04
I downloaded my installer ova from here yesterday. Looks like it hasn't been updated since jan 20th. is there somewhere else I should get the installer from? .... thank you!

https://github.com/vmware/photon-controller/releases/tag/v1.1.1

**Comment by schadr** [comment] 2017-03-30 15:32
The installer was updated a couple of days ago, the Jan 20th is just the date the original release was created.

This is the installer that was uploaded
https://github.com/vmware/photon-controller/releases/download/v1.1.1/installer-ova-nv-1.1.1-cfb7512.ova

**Comment by ShaorongChen** [comment] 2017-04-05 06:02
Downloaded and deployed the latest OVA, installer-ova-nv-1.1.1-cfb7512.ova

Tried the deployment, lightwave, photon-controller, and load balancer was deployed but failed at the last stage with a message,
2017-04-05 05:51:28 ERROR ControllerInstaller:540 - Failed in provisioning host: LSSINH020.sin.sap.corp

[pc-config.yaml_5Apr.txt](https://github.com/vmware/photon-controller/files/895290/pc-config.yaml_5Apr.txt)
[photon-installer_5Apr.log.txt](https://github.com/vmware/photon-controller/files/895291/photon-installer_5Apr.log.txt)

**Comment by AlainRoy** [comment] 2017-04-05 13:35
What version of ESXi do you have deployed. 1.1.1 requires 6.0u2p4 (build 4600944). Later builds might work. 

How many DNS servers did you have pre-configured on the ESXi host before you started? It must be less than three.

**Comment by ShaorongChen** [comment] 2017-04-06 04:50
Hi,
I have 2 dns configured, that should be fine.

But my ESXi host is current on 6.0u1 could not update it anytime soon. I have to wait for the next quarter maintenance cycle.

I will try again once i get the downtime to upgrade the hosts.
Thanks.

**Comment by AlainRoy** [comment] 2017-04-06 18:36
I'm glad we found the problem. Sorry for the inconvenience! There was a bug fix in 6.0u2p4 that we require.

**Closed by AlainRoy** 2017-04-06 18:36 UTC
