### ISSUE TITLE
UI broken on non-EN locale

### ISSUE THREAD

**Issue by ruurdk** [vmware/photon-controller#22] opened 2016-04-13 13:22 UTC
When set to a non-EN locale (in my case it was NL), the UI breaks.

On the controller the effects are limited to not displaying texts correctly, but the installer UI breaks completely. 

A browser network trace shows:
GET http://<installer-ip>/locale/locale-nl.json 404 (Not Found)

![image](https://cloud.githubusercontent.com/assets/7431874/14494496/66a685b2-018b-11e6-9dff-cc4c4a299c36.png)
![image](https://cloud.githubusercontent.com/assets/7431874/14494522/7d54aa8c-018b-11e6-85ad-e6310eb6fffd.png)

**Comment by kmjung** [comment] 2016-04-13 16:47
Thanks for reporting this! I filed a bug in our tracker for this issue: https://www.pivotaltracker.com/story/show/117550215

**Comment by vigie** [comment] 2016-04-13 17:27
We have root caused the issue and updated the associated pivotal tracker issue (linked above).

In the meantime please use this workaround: add "?lang=en" to the end of the URL when launching either app to force the strings to render in English. 

Closing this issue as corresponding source code is not yet in this repo - please track fix using pivotal tracker link. However, please comment further if you have problems with the above workaround. Thanks.

**Closed** 2016-04-13 18:22 UTC

**Comment by haarchri** [comment] 2016-08-17 14:41
issue is not solved yet - same issue with german browser language - i have no access to pivotaltracker - have you an update for the issue ?
