### ISSUE TITLE
Web page of the Photon Controller portal rendered with errors

### ISSUE THREAD

**Issue by RedDevil69** [vmware/photon-controller#94] opened 2017-02-28 12:17 UTC
Navigation bars titles and other elements on web page of the photon controller is rendered not properly.
On one setup everything is fine, I instilled jump host with win 2012 and win 10 and  have completely different view plus js warnings in console:

...
Translation for esxcloud.mgmtApp.cloud.hosts doesn't exist  app-5490c887c0.js:63:19799
Translation for esxcloud.mgmtApp.cloud.networks doesn't exist  app-5490c887c0.js:63:19799
Translation for esxcloud.mgmtApp.cloud.hosts doesn't exist  app-5490c887c0.js:63:19799
Translation for esxcloud.mgmtApp.cloud.networks doesn't exist  app-5490c887c0.js:63:19799
...

![image](https://cloud.githubusercontent.com/assets/15016336/23404989/30257ef6-fdb8-11e6-8c38-77c5df7639a1.png)

**Comment by RedDevil69** [comment] 2017-02-28 14:12
Found on my own.
The problem is locale of the web browser, switching to English (United States) resolved the issue.
BTW: This is bug :)

**Comment by AlainRoy** [comment] 2017-02-28 14:46
Our UI team knows about this bug. I believe it's fixed internally and will be in a future release, but I'm not sure. I'll check with them to be sure.

**Closed by AlainRoy** 2017-02-28 14:46 UTC

**Comment by AlainRoy** [comment] 2017-02-28 16:45
Duplicate of: https://github.com/vmware/photon-controller/issues/22
